name: Release grappledog APWorld
on:
  push:
    tags:
      - '**'
jobs:
  release:
    uses: Eijebong/ap-actions/.github/workflows/release-apworld.yml@main
    with:
      apworld-path: worlds/grappledog
      ap-version: '0.6.6'
      python-version: '3.12'